version: '3'

services:
  docker-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db_example
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
    ports:
      - 3306:3306
    networks:
      - springmysql-net-3

  app:
    image: backend:latest
    ports:
       - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db_example?autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
    networks:
       - springmysql-net-3

#Docker Networks
networks:
    springmysql-net-3:
        driver: bridge