apiVersion: v1
kind: Service
metadata:
  name: car-service
  labels:
    app: car-service
spec:
  selector:
    app: car-deployment
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8001
  type: LoadBalancer
